version: '3.9'
services:
  face_recog:
    image: blipshare/robohome-fr:edge
    build:
      context: fr
      dockerfile: Dockerfile.edge
    container_name: robohome-fr
    environment:
      - WORKERS=2
      - HOST=0.0.0.0
      - PORT=9900
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data:/app/data
    ports:
      - 0.0.0.0:9900:9900

  dashboard:
    image: blipshare/robohome-dashboard:edge
    build:
      context: .
      dockerfile: Dockerfile.edge
    container_name: dashboard
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data:/app/data
    ports:
      - 0.0.0.0:443:443
    links:
      - "face_recog"
