FROM alpine:edge as builder

ARG USERNAME=node
ARG GROUP=node

RUN addgroup -S $GROUP && \
    adduser -S $USERNAME -G $GROUP

COPY . /app

WORKDIR /app

RUN /bin/sh ./scripts/build_edge.sh && \
    chown -R $USERNAME /app

# Set the default user.
USER $USERNAME

