version: '3.9'

services:
  home-automation:
    image: nginx:latest
    container_name: home-automation
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vue3/dist:/usr/share/nginx/html
      - .nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
    restart: on-failure
